-- Lisää DROP TABLE lauseet tähän tiedostoon
DROP TABLE IF EXISTS Account CASCADE;
DROP TABLE IF EXISTS Tasklist CASCADE;
DROP TABLE IF EXISTS Task CASCADE;
DROP TABLE IF EXISTS Category CASCADE;
DROP TABLE IF EXISTS Connect CASCADE;
